### ISSUE TITLE
Integration not working anymore, failed to start

### ISSUE THREAD

**Issue by 0p3t0** [DurgNomis-drol/ha_toyota#160] opened 2023-10-06 20:22 UTC
Starting from 2nd october the integration is not able anymore to start

![image](https://github.com/DurgNomis-drol/ha_toyota/assets/59409205/790e11ea-1d33-48f6-852e-78d03ea1ee58)
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/59409205/34ba9d47-2801-4f5d-92c8-92a7cf02d532)
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/59409205/b34e978e-8bf8-4a5a-8313-26cebac4cb76)

Checking debug log this is relevant lines:
2023-10-06 22:13:28.819 DEBUG (MainThread) [custom_components.toyota] The car is reporting data in metric
2023-10-06 22:13:31.965 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: HTTP: 400 - {"timestamp":1696623211942,"status":400,"error":"Bad Request","message":"No device associated with VIN","errorCode":"CMA400"}
2023-10-06 22:13:31.966 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 7.722 seconds (success: False)

Please let me know if you need more details, I'm glad to help :)
Best regards

**Comment by AdrianStanciu22** [comment] 2023-10-07 10:12
Same issue

**Comment by vix66** [comment] 2023-10-07 17:06
Same issue

**Comment by mario-pranjic** [comment] 2023-10-08 12:23
+1

**Comment by mario-pranjic** [comment] 2023-10-19 07:15
Any feedback on this one? This integration is completely broken in my setup.

**Comment by AdrianStanciu22** [comment] 2023-10-19 17:14
Just few people encounter this trobuble?

**Comment by SrvRpi** [comment] 2023-10-20 12:50
Same. It works very unstable, constantly losing connection.

**Comment by rbrymora** [comment] 2023-10-22 14:33
+1, stopped working 2-3 weeks ago.

**Comment by hercza** [comment] 2023-10-24 15:55
+1, same problem here!

**Comment by panosru** [comment] 2023-10-25 17:57
Same for me...
2023-10-25 20:54:40.786 ERROR (MainThread) [custom_components.toyota] Error fetching toyota data: Update canceled! Toyota's API was too slow to respond. Will try again later...

![image](https://github.com/DurgNomis-drol/ha_toyota/assets/400362/64baf495-1ad4-4556-8503-5174ffd73671)

**Comment by SrvRpi** [comment] 2023-10-31 07:50
Again ...

Logger: custom_components.toyota
Source: helpers/update_coordinator.py:322
Integration: Toyota Connected Services (documentation, issues)
First occurred: 9:40:29 AM (6 occurrences)
Last logged: 9:48:19 AM

Error fetching toyota data: Update canceled! Toyota's API was too slow to respond. Will try again later...

**Comment by briandelicata** [comment] 2023-11-20 15:09
I am still receiving this error even on the latest master. "HTTP: 400 - {"timestamp":1700492682007,"status":400,"error":"Bad Request","message":"No device associated with VIN","errorCode":"CMA400"}"

However if debug logging is enabled, the car details and sensors data are shown for only one of my cars registered on the new MyToyota app.

**Comment by renewoensdregt** [comment] 2023-12-01 09:49
It doesn´t work for me either, but with a different message : 

Source: custom_components/toyota/__init__.py:89
Integration: Toyota Connected Services ([documentation](https://github.com/DurgNomis-drol/ha_toyota), [issues](https://github.com/DurgNomis-drol/ha_toyota/issues))
First occurred: November 22, 2023 at 16:31:26 (928 occurrences)
Last logged: 10:42:58

Please setup Connected Services if you want live data from the car. (********)

**Comment by andyz68** [comment] 2023-12-25 08:18
It doesn't work for me to.
I installed the last version 1.3.0, i'm able to do the login but the integration doesn't work with this message "failed to setup"

I tryed to reinstall the intergration and to restart HA with the same issue.

![Screenshot 2023-12-25 091107](https://github.com/DurgNomis-drol/ha_toyota/assets/74782864/f1cc01da-0e56-4c7c-8e88-8885399514e7)
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/74782864/a4e8e73c-0240-470e-be15-3bf60841495d)

HA Version
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/74782864/b9537e50-606b-40c0-b47d-3043d5a4f18b)

**Comment by DanielePalombo** [comment] 2023-12-26 09:57
Same here!

**Comment by mario-pranjic** [comment] 2023-12-26 16:31
+1.

Getting "Failed to setup" after completing setup process and entering username/password.
No additional info in logs this time.

**Comment by CM000n** [comment] 2023-12-26 19:38
Presumably the old API endpoints are gradually being switched off or neglected by Toyota. It is unlikely that we will make a fix for this.
The next goal is to switch to the new Toyota API endpoints.

**Comment by mario-pranjic** [comment] 2023-12-26 19:58
That is funny, since I have been migrated to new Toyota App at least month ago. The old one doesn't work anymore for me.

**Comment by CM000n** [comment] 2023-12-26 20:24
> That is funny, since I have been migrated to new Toyota App at least month ago. The old one doesn't work anymore for me.

Sorry, I don't understand. What's so funny about that?

**Comment by mario-pranjic** [comment] 2023-12-26 20:43
Well, I would expect it to work as intended after migration on Toyota side and new version of component here, but it fails, and are bit confused what might be the cause.

**Comment by CM000n** [comment] 2023-12-26 21:03
> Well, I would expect it to work as intended after migration on Toyota side and new version of component here, but it fails, and are bit confused what might be the cause.

Why should that work? We are in no way officially affiliated with Toyota and there is no official documentation of the API endpoints.
For these reasons, the Home Assistant component has not yet been converted to the new API endpoints. 
We are currently still gaining our knowledge through trial and error and will probably only be able to start adapting the Home Assistant component to the new endpoints in the next few weeks.

**Comment by disi** [comment] 2023-12-30 18:44
I just add myself to the list with my Toyota Corolla :) Version 1.3 -> new app.

**Comment by luigisax** [comment] 2024-01-02 10:54
same issue, yaris cross - v 1.3 - new app

**Comment by BarbaGrump** [comment] 2024-01-02 11:17
chiming in...RAV4, new app

**Comment by SrvRpi** [comment] 2024-01-02 11:21
Same. CH-R  v1.3

**Comment by radzio** [comment] 2024-01-02 12:17
Same here, RAV4 
```
2024-01-02 13:15:22.909 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 0.947 seconds (success: False)
2024-01-02 13:15:29.719 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 1.037 seconds (success: False)
2024-01-02 13:15:42.132 DEBUG (MainThread) [custom_components.toyota] Finished fetching toyota data in 1.467 seconds (success: False)
```

**Comment by mork993** [comment] 2024-01-06 19:12
Same issue with yaris cross - v 1.3 - new app

**Comment by jdoebv2** [comment] 2024-01-13 14:21
Same for me with v 1.3. …..failed to setup. 
 Authentication works because if I use the wrong password I get an error message.

**Comment by CM000n** [comment] 2024-01-13 16:02
From my side, the pull request with the changes for the new Toyota API would be ready for merging: https://github.com/DurgNomis-drol/ha_toyota/pull/198
Currently I'm just waiting until @DurgNomis-drol has time for a review to approve the PR.
But if you want, you can already test it manually. 😊

**Closed** 2024-01-14 18:42 UTC
Labels: :bug: bug

**Comment by 0p3t0** [comment] 2024-01-15 14:24
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/59409205/fc35e8bf-aefc-4161-b25b-643525e800ce)
Unfortunately also with v2.0.0 still not working
![image](https://github.com/DurgNomis-drol/ha_toyota/assets/59409205/f8c3660d-daee-40b0-9899-f94af049e36b)

**Comment by renewoensdregt** [comment] 2024-01-15 14:27
> ![image](https://private-user-images.githubusercontent.com/59409205/296778435-fc35e8bf-aefc-4161-b25b-643525e800ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjkwNjcsIm5iZiI6MTcwNTMyODc2NywicGF0aCI6Ii81OTQwOTIwNS8yOTY3Nzg0MzUtZmMzNWU4YmYtYWVmYy00MTYxLWIyNWItNjQzNTI1ZTgwMGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE0MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NTZlZjZlYmI4ZTJiNDMxMTU1YTNiZGFlNzVjNWNiODFmZmYwMWM5MDYyM2Q2NjRhOWI4NzRhMjBiYjExNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V1MfpekZQAKKaKT15J_4K5c8pbDKqtNqenT9hdZKBkw) Unfortunately also with v2.0.0 still not working ![image](https://private-user-images.githubusercontent.com/59409205/296782683-f8c3660d-daee-40b0-9899-f94af049e36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjkwNjcsIm5iZiI6MTcwNTMyODc2NywicGF0aCI6Ii81OTQwOTIwNS8yOTY3ODI2ODMtZjhjMzY2MGQtZGFlZS00MGIwLTk4OTktZjk0YWYwNDllMzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE0MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4Y2I3MjlhYTc2ZTA4NzQ1MjgzMjkxNDI0NzVjMzRiNWFiY2JkMjgzZWUxMWVkMWZlZTQwNzczZWIwMjIyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aBhJqdLZoIcKOObR0dCIsnyrnS6tf6eIn1sT15NxCfI)

I had the same issue. I resolved it by first deleting the old integration from integrations and HACS, then rebooted HA fully and once done added the addon to HACS again and then in the integration and now it completely works fine.

**Comment by CM000n** [comment] 2024-01-15 15:11
> Unfortunately also with v2.0.0 still not working ![image](https://private-user-images.githubusercontent.com/59409205/296782683-f8c3660d-daee-40b0-9899-f94af049e36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzE3MDIsIm5iZiI6MTcwNTMzMTQwMiwicGF0aCI6Ii81OTQwOTIwNS8yOTY3ODI2ODMtZjhjMzY2MGQtZGFlZS00MGIwLTk4OTktZjk0YWYwNDllMzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE1MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzg0ZTkyMWYxMDM0OWQyZjUwYjIyMGFlODY0MDEwYTlhZTI5NWVhYWVkZjZiNThmOGJhZDQyZWZkMjJhZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aqlz1y3c5e3qYQ4640CG2UXbfv1D62zd_CBnR3ItAZg)

Someone else who hasn't read the changelog properly https://github.com/DurgNomis-drol/ha_toyota/releases/tag/v2.0.0 😉 😛
