### ISSUE TITLE
not starting after update to core-2021.11.3

### ISSUE THREAD

**Issue by kapanikos** [DurgNomis-drol/ha_toyota#81] opened 2021-11-12 13:40 UTC
Today after updating the core of home assistant to core-2021.11.3 the toyota integration does not start anymore.
This occurs even after restarting the server, rebooting the host or reinstalling the integration.

Following errors are logged:

Logger: homeassistant.config_entries
Source: custom_components/toyota/__init__.py:62
Integration: Toyota Connected Services (documentation, issues)
First occurred: 14:33:03 (1 occurrences)
Last logged: 14:33:03

Error setting up entry something@somewhere.com for toyota
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/toyota/__init__.py", line 62, in async_setup_entry
    client = MyT(
  File "/usr/local/lib/python3.9/site-packages/mytoyota/client.py", line 55, in __init__
    raise ToyotaLocaleNotValid(
mytoyota.exceptions.ToyotaLocaleNotValid: Please provide a valid locale string! Valid format is: en-gb.

Kind regards
Kapa

**Comment by DurgNomis-drol** [comment] 2021-11-12 13:41
Duplicate of #75

Follow #75 for updates 😊

**Closed by DurgNomis-drol** 2021-11-12 13:41 UTC
