### ISSUE TITLE
Entities not available

### ISSUE THREAD

**Issue by PGutti** [DurgNomis-drol/ha_toyota#83] opened 2021-11-14 08:29 UTC
**Intro**
After installing this integration it worked perfectly.  Until one day it did not.  I cannot say what exactly i have done: I updated various parts of HA and i installed other add-ons and integrations.
To solve i re-installed the extension... without any visible improvement. 

**Bug**
Instead of the name and the value of the sensors i get: Entity not available: binary_sensor.rav4_xxxxx
After writing this i tried to create a new card.  And could not find any RAV4 sensor anymore!!

**To Reproduce**
Create a card with multiple entities, select any from the pulldown list.

![Captura 2021-11-14 a las 9 17 55](https://user-images.githubusercontent.com/40051675/141673405-bfd9a803-e6af-472d-860f-456dea5ad58b.jpg)
![Captura 2021-11-14 a las 9 18 07](https://user-images.githubusercontent.com/40051675/141673412-f547b49e-5bb3-4532-8390-b7aa6fea2e73.jpg)
![Captura 2021-11-14 a las 9 27 06](https://user-images.githubusercontent.com/40051675/141673638-abc2054e-5d08-42fa-bc12-29250f46d313.jpg)
![Captura 2021-11-14 a las 9 28 18](https://user-images.githubusercontent.com/40051675/141673644-034a2ad6-e436-40ea-9d3b-ce1916d1aece.jpg)
![Captura 2021-11-14 a las 9 27 38](https://user-images.githubusercontent.com/40051675/141673642-10d2059f-fee5-4fbd-babe-2597a45f3ff9.jpg)

**Comment by DurgNomis-drol** [comment] 2021-11-14 09:07
Post your logs

**Comment by homonto** [comment] 2021-11-14 19:39
Hi there,

Few days ago, after last update to HA 2021.11 this integration stopped working - cannot login anymore with strange error (see below) - no changes have been made on HA apart from its regular update to the latest release:
![Screenshot 2021-11-14 at 19 34 06](https://user-images.githubusercontent.com/46562447/141695858-b1b1907d-d545-4e77-bab4-ef1c9029b75a.jpg)

**Comment by homonto** [comment] 2021-11-14 19:41
two more screens - I think it shows where the problem is:
![Screenshot 2021-11-14 at 19 41 09](https://user-images.githubusercontent.com/46562447/141695936-6a837252-babc-4ec1-80bb-c6482ab1bdd8.jpg)
![Screenshot 2021-11-14 at 19 41 22](https://user-images.githubusercontent.com/46562447/141695938-38d4fb67-9ce0-4011-81ff-f0b1b5d50932.jpg)

**Comment by DurgNomis-drol** [comment] 2021-11-14 20:44
This was just fixed in the latest release, please update 😊

**Comment by homonto** [comment] 2021-11-14 20:51
done - thank you ;-)

**Comment by DurgNomis-drol** [comment] 2021-11-14 20:53
Good to hear, will keep this open to make sure he is not having another separate problem, though i suspect it is the same. 😊

**Comment by DurgNomis-drol** [comment] 2021-11-23 17:44
@PGutti Do you still have this issue?

**Comment by PGutti** [comment] 2021-11-23 18:41
No!  All variables/sensores now contain a value. Super.  

Regards
Peter

**Closed** 2021-11-23 18:46 UTC
