### ISSUE TITLE
Error «Please setup Connected Services» after Migration to new MyToyota App/API

### ISSUE THREAD

**Issue by uphillbattle** [DurgNomis-drol/ha_toyota#164] opened 2023-10-29 11:31 UTC
**Describe the bug**
The Toyota integration has stopped working, seems to have happened at the same time as the car was moved (by Toyota) from the «MyT Toyota» app to the «MyToyota» app.
I get this error message in the logs:
```
2023-10-29 12:27:21.691 ERROR (MainThread) [mytoyota] Please setup Connected Services if you want live data from the car. (JTM**************)
```

**Comment by lucianlazar1983** [comment] 2023-10-29 12:33
What country are you in? I don't see any my toyota app, only myT on apple app store--Lucian Lazar – Senior Solution ArchitectecoIT Solutions Srl@***@***.***  +40770558273‬www https://ecoit.solutionsOn Oct 29, 2023, at 13:31, Tom ***@***.***> wrote:﻿
Describe the bug
The Toyota integration has stopped working, seems to have happened at the same time as the car was moved (by Toyota) from the «MyT Toyota» app to the «MyToyota» app.
I get this error message in the logs:
2023-10-29 12:27:21.691 ERROR (MainThread) [mytoyota] Please setup Connected Services if you want live data from the car. (JTM**************)

**Comment by uphillbattle** [comment] 2023-10-29 14:43
Norway. I noticed that all the Toyota sensors in HA were unavailable. I opened the MyT app to see what I could see and was met by a notification that car was moved to the MyToyota app and that I should download that. After doing that and logging in, I can see the car and its data in the new MyToyota app, but the HA integration is unsuccessful - with the error message in the OP.

**Comment by uphillbattle** [comment] 2023-10-29 15:15
I can’t anymore set up the car in the old MyT app. If I try, it responds with a message saying I have to use the new MyToyota app. I’m wondering if Toyota have set up a new API and are moving cars to the new app (perhaps staged somehow - for example by country).

**Comment by CM000n** [comment] 2023-11-01 11:23
I have the same behavior here in Germany after my vehicle was migrated to the new MyToyota app last week:
https://play.google.com/store/apps/details?id=com.toyota.oneapp.eu

Since then no connection with the Home Assistant custom component is possible.
Since the custom component was only a reverse engeneering of the old Toyota app by @DurgNomis-drol possible, I don't know if he will find the time again to do that for them new app again. :-(

Maybe we should all write to Toyota via different channels and ask them to finally provide us with an official API!

**Comment by CM000n** [comment] 2023-11-01 11:43
I just wrote an email to Toyota. Let's see if something comes back:

> Official API for Toyota Connected Services?

Simon <simon> Mi., 1. Nov. 2023 um 12:40
An: MyTapp@toyota-europe.com
Dear Toyota App Team,
the new MyToyota App is in itself a nice revision of the previous MyT App.
However, Toyota seems to have also changed the API here in the background.
This poses problems for developers who offer solutions based on reverse engineering of the old MyT app. They now have to start
all over again.
For example, the Home Assistant Toyota integration, which is used by several thousand people, is no longer functional after a
migration to the new MyToyota API: https://github.com/DurgNomis-drol/ha_toyota/issues/164
As mentioned, the MyToyota app is quite nice, but for those who want to go a step further and integrate their Toyota really "smart"
into the rest of their smart home ecosystem, it is unfortunately insufficient.
So would it please be possible to finally provide us with an official API for Toyota Connected Services?
You would really endear yourselves to some people and really show a will to innovate.
Best regards and many thanks in advance!
Simon

**Comment by CM000n** [comment] 2023-11-01 18:58
Hi @DurgNomis-drol, sorry to hear that, but totally understandable!
Unfortunately, I currently also have little time and will probably not be able to take care of an adaptation to the new API.

By the way, the migration of the vehicles to the new App/API takes place without any active interactions @DurgNomis-drol.
One morning when I opened the MyT app, it simply told me to use the new app. So it's quite possible that your Aygo will be migrated soon as well ;-)

**Comment by DurgNomis-drol** [comment] 2023-11-02 15:32
@CM000n Well then I will try not to open the App 😉 or I will have a winter project on my hand again 😆 🚀

**Comment by m-dietrich** [comment] 2023-11-03 09:06
I checked my app, and my corolla has not been moved yet, but from what i can read here, this might happen within the next days.

When this happens, maybe i can provide informations, or also can help to code a library for the new api.
Let us find out, what will happen.

**Comment by nielsvdc** [comment] 2023-11-03 12:24
I moved to the new MyTotota app after buying a Corolla this week. I added the HA integration and logged in with my Toyota credentials. I only get one entity: sensor.corolla_numberplate. The rest is not loaded or available.

![image](https://github.com/DurgNomis-drol/ha_toyota/assets/10850600/cb8f2a72-e6d4-45a3-ad7c-02ce5af3523b)

**Comment by uphillbattle** [comment] 2023-11-04 07:33
@nielsvdc This is exactly what I see as well, with a bZ4x

**Comment by uphillbattle** [comment] 2023-11-07 17:28
I haven't look in the .apk file like you have, @CM000n, but I played around with the old API a bit and noticed that the "legacy" endpoint `https://myt-agg.toyota-europe.com/cma/api/vehicles/${"vin"}/remoteControl/status` still includes charge status and remaining distance (for my bZ4x):

```
{
    "VehicleInfo": {
        "AcquisitionDatetime": "2023-11-07T12:38:17Z",
        "RemoteHvacInfo": {
            "Temperaturelevel": 33,
            "RemoteHvacMode": 0,
            "RemoteHvacProhibitionSignal": 1,
            "SettingTemperature": 22.0,
            "BlowerStatus": 0,
            "FrontDefoggerStatus": 0,
            "RearDefoggerStatus": 0,
            "InsideTemperature": 26
        },
        "ChargeInfo": {
            "EvDistanceInKm": 446.1,
            "GasolineTravelableDistanceUnit": 1,
            "GasolineTravelableDistance": 0,
            "PlugStatus": 45,
            "PlugInHistory": 33,
            "RemainingChargeTime": 65535,
            "EvTravelableDistance": 446.1,
            "EvTravelableDistanceSubtractionRate": 18,
            "ChargeRemainingAmount": 100,
            "SettingChangeAcceptanceStatus": 0,
            "ChargeType": 15,
            "ChargeWeek": 0,
            "ChargeStartTime": "42:35",
            "ChargeEndTime": "42:35",
            "ConnectorStatus": 5,
            "BatteryPowerSupplyPossibleTime": 16383,
            "ChargingStatus": "chargeComplete",
            "EvDistanceWithAirCoInKm": 365.8
        }
    },
    "ReturnCode": "000000"
}
```

Don't know how long that will last, though.

**Comment by CM000n** [comment] 2023-11-07 18:11
> I haven't look in the .apk file like you have, @CM000n, but I played around with the old API a bit and noticed that the "legacy" endpoint `https://myt-agg.toyota-europe.com/cma/api/vehicles/${"vin"}/remoteControl/status` still includes charge status and remaining distance (for my bZ4x):

Good finding @uphillbattle ! If I have time, I'll play around with the old API endpoint tomorrow too.

By the way: I was just about to visit our friends at Toyota Home Assistant Integration for North America to see which endpoints are used there.
I was shocked to see that the Gut repo was shut down with a DMCA notification: https://github.com/widewing/toyota-na
Let's hope Toyota Europe doesn't take similar steps.

**Comment by DurgNomis-drol** [comment] 2023-11-08 10:52
Well now I got the email, but I haven't opened the app, and it still seems to work, so I believe it only moves you to the new app if you open the old one 🎉

**Comment by m-dietrich** [comment] 2023-11-09 09:28
I can confirm up to now.
Mail with the notification for shutdown of the old app has arrived.
Maybe i have now a weekend-project.

**Comment by CM000n** [comment] 2023-11-09 11:56
Hi @DurgNomis-drol and @m-dietrich,

I took another look today and I think we are dealing with two problems here:

**1. The “Please setup Connected Services …” error**

This error occurs because the structure of the data returned by the API has changed. This causes a check to see whether Connected Services are activated in the `mytoyota` Python lib to fail. I've just created a pull request for this with a possible fix: https://github.com/DurgNomis-drol/mytoyota/pull/240
However, this still needs to be merged and the `ha_toyota` custom component needs to be adjustet so that it uses the latest version of the `mytoyota` lib. This may require major adjustments as `ha_toyota` is currently using an outdated version of the `mytoyota` lib. What is your assessment of drugnomis here @DurgNomis-drol?

**2. Changed API Endpoint for vehicle's trips?**

At first I thought we were dealing with a changed API endpoint here. 
However, after I used the above fix locally, the following minimal example including the information about the vehicle's journeys also worked:

```python
import asyncio
from pprint import pprint
from mytoyota.client import MyT

username = "USERNAME"
password = "PASSWORD"
brand = "toyota"  # or lexus

# Get supported regions, can be passed to the optional 'region' argument of MyT
# At this moment, only the 'europe' region is supported
pprint(MyT.get_supported_regions())

client = MyT(username=username, password=password, brand=brand)

async def get_information():
    pprint("Logging in...")
    await client.login()

    pprint("Retrieving cars...")
    # Returns cars registered to your account + information about each car.
    cars = await client.get_vehicles()
    pprint(cars)

    for car in cars:

        vehicle = await client.get_vehicle_status(car)
        # Information on vehicle status object continues to work:
        pprint("Vehicle Info..")
        pprint(vehicle._vehicle_info)
        pprint("Connected Services..")
        pprint(vehicle._connected_services)
        pprint("Odometer..")
        pprint(vehicle.odometer)
        pprint("Status..")
        pprint(vehicle._status)
        pprint("Status Legacy..")
        pprint(vehicle._status_legacy)

        pprint(vehicle.dashboard.odometer)

        # Statistics still don't seem to work due to a changed API endpoint?

        data = await asyncio.gather(
            *[
                client.get_driving_statistics(vehicle.vin, interval="day"),
                client.get_driving_statistics(vehicle.vin, interval="isoweek"),
                client.get_driving_statistics(vehicle.vin),
                client.get_driving_statistics(vehicle.vin, interval="year"),
            ]
        )
        pprint(data)

        # Daily stats
        daily_stats = await client.get_driving_statistics(vehicle.vin, interval="day")
        pprint(daily_stats)
        # ISO 8601 week stats
        iso_weekly_stats = await client.get_driving_statistics(vehicle.vin, interval="isoweek")
        pprint(iso_weekly_stats)
        # Monthly stats is returned by default
        monthly_stats = await client.get_driving_statistics(vehicle.vin)
        pprint(monthly_stats)
        # Get year to date stats.
        yearly_stats = await client.get_driving_statistics(vehicle.vin, interval="year")
        pprint(yearly_stats)

loop = asyncio.get_event_loop()
loop.run_until_complete(get_information())
loop.close()
```
So it seems that we don't have to look for a new API endpoint for the trip statistics (for now).

**Comment by GitOldGrumpy** [comment] 2023-11-09 11:58
The attached will get you connected to the new toyota services. You need to enter your username, password and GUID at the top of the file. The problem is the GUID this is your customer ID but I have yet to work out how the toyota app knows what this is! You can find it by logging into My Toyota website and in the developer tools find a request for `https://cpb2cs.toyota-europe.com/vehicle/user/<This Will Be Your GUID>/...`. It may contain much more than is required but allows to me check the two accounts I have access too.

`import requests
import json
import urllib.parse
import pprint

def pretty_print_POST(req):
    print('{}\n{}\r\n{}\r\n\r\n{}'.format(
        '-----------START-----------',
        req.method + ' ' + req.url,
        '\r\n'.join('{}: {}'.format(k, v) for k, v in req.headers.items()),
        req.body,
    ))
    
    
USERNAME="<username>"
PASSWORD="<password>"
GUID="<guid>"


pp = pprint.PrettyPrinter(indent=4)
session = requests.Session()
headers = {
		   "accept-api-version": "resource=2.1, protocol=1.0",
		   "x-brand": "T",
		   "content-type": "application/json; charset=utf-8",
		   "accept-encoding": "gzip",
		   "user-agent": "okhttp/4.10.0",
		  }


server = "https://b2c-login.toyota-europe.com"

# HEADERS[3]
#print("1 ----- 1")
url1 = "/json/realms/root/realms/tme/authenticate?authIndexType=service&authIndexValue=oneapp"
req1 = requests.Request("POST", server + url1, headers=headers)
prep1 = req1.prepare()
resp1 = session.send(prep1)
assert(resp1.status_code == 200)
dict1 = json.loads(resp1.text)
#print(dict1)


# HEADERS[5]
#print("\n2 ----- 2")
url2 = "/json/realms/root/realms/tme/authenticate?authIndexType=service&authIndexValue=oneapp"
data2 = {"authId":dict1["authId"],"callbacks":[{"type":"NameCallback","output":[{"name":"prompt","value":"Market Locale"}],"input":[{"name":"IDToken1","value":"GB"}],"_id":0},{"type":"NameCallback","output":[{"name":"prompt","value":"Internationalization"}],"input":[{"name":"IDToken2","value":"en-GB"}],"_id":1},{"type":"NameCallback","output":[{"name":"prompt","value":"UI Locales"}],"input":[{"name":"IDToken3","value":"en"}],"_id":2}]}
req2 = requests.Request("POST", server + url2, data=json.dumps(data2), headers=headers)
prep2 = req2.prepare()
resp2 = session.send(prep2)
assert(resp2.status_code == 200)
dict2 = json.loads(resp2.text)
#print(dict2)

# HEADERS[7]
#print("\n3 ----- 3")
url3 = "/json/realms/root/realms/tme/authenticate"
data3 = {"authId":dict2["authId"],"callbacks":[{"type":"NameCallback","output":[{"name":"prompt","value":"User Name"}],"input":[{"name":"IDToken1","value":USERNAME}],"_id":3},{"type":"ChoiceCallback","output":[{"name":"prompt","value":"Prompt"},{"name":"choices","value":["Local","Google","Facebook","Apple"]},{"name":"defaultChoice","value":0}],"input":[{"name":"IDToken2","value":0}],"_id":4}]}
req3 = requests.Request("POST", server + url3, data=json.dumps(data3), headers=headers)
prep3 = req3.prepare()
resp3 = session.send(prep3)
assert(resp3.status_code == 200)
dict3 = json.loads(resp3.text)
#print(dict3)

# HEADERS[9]
#print("\n4 ----- 4")
url4 = "/json/realms/root/realms/tme/authenticate"
data4 = {"authId":dict3["authId"],"callbacks":[{"type":"PasswordCallback","output":[{"name":"prompt","value":"Password"}],"input":[{"name":"IDToken1","value":PASSWORD}],"_id":5},{"type":"ChoiceCallback","output":[{"name":"prompt","value":"Prompt"},{"name":"choices","value":["continue","resetpass"]},{"name":"defaultChoice","value":0}],"input":[{"name":"IDToken2","value":0}],"_id":6}]}
req4 = requests.Request("POST", server + url4, data=json.dumps(data4), headers=headers)
prep4 = req4.prepare()
resp4 = session.send(prep4)
assert(resp4.status_code == 200)
dict4 = json.loads(resp4.text)
#print(dict4)

# HEADERS[11]
#print("\n5 -----5 ")
url5 = "/oauth2/realms/root/realms/tme/authorize?client_id=oneapp&scope=openid profile write&response_type=code&redirect_uri=com.toyota.oneapp:/oauth2Callback&code_challenge=CfIzFZNt0wD4TtMg49PYvR-xQglTQdqL9blKZx0oqIk&code_challenge_method=S256"
headers5 = headers.copy()
headers5["cookie"] = "iPlanetDirectoryPro=" + dict4["tokenId"]
req5 = requests.Request("GET", server + url5, headers=headers5)
prep5 = req5.prepare()
resp5 = session.send(prep5, allow_redirects=False)
assert(resp5.status_code == 302)
up = urllib.parse.urlparse(resp5.headers["location"])
qs = urllib.parse.parse_qs(up.query)["code"][0]
#print(qs)

# HEADERS[13]
#print("\n6 -----6 ")
url6 = "/oauth2/realms/root/realms/tme/access_token"
headers6 = headers.copy()
headers6["content-type"] = "application/x-www-form-urlencoded"
headers6["authorization"] = "basic b25lYXBwOm9uZWFwcA=="
data6={"client_id": "oneapp",
       "code": qs,
       "redirect_uri": "com.toyota.oneapp:/oauth2Callback",
       "grant_type": "authorization_code",
       "code_verifier": "vOVtatZC5dAFHPNDSZeWs9wOpchaOv4-B4GwjL2Ky0cVqXP8tfmRtFQOfe5RFw5aXS_cPoFEZcQP9ezggMOPrg"}
req6 = requests.Request("POST", server + url6, data=data6, headers=headers6)
prep6 = req6.prepare()
#pretty_print_POST(prep6)
resp6 = session.send(prep6)
assert(resp6.status_code == 200)
dict6 = json.loads(resp6.text)
#pp.pprint(dict6)


# Yeah I think we have the auth token!!!
# Can we get telemetetry?
#print("\n7 -----7")
#url7 = "/v4/account"
url7 = "/v2/vehicle/guid"
headers7 = {"x-api-key": "tTZipv6liF74PwMfk9Ed68AQ0bISswwf3iHQdqcF",
        	"x-device-timezone": "GMT",
        	"accept": "application/json",
			"x-guid": GUID,
			"authorization": "Bearer " + dict6["access_token"],
        	"accept-encoding": "gzip",
	        "user-agent": "okhttp/4.10.0"}
req7 = requests.Request("GET", "https://ctpa-oneapi.tceu-ctp-prd.toyotaconnectedeurope.io" + url7, headers=headers7)
prep7 = req7.prepare()
#pretty_print_POST(prep7)
resp7 = session.send(prep7)
#assert(resp7.status_code == 200)
dict7 = json.loads(resp7.text)
pp.pprint(dict7)`

**Comment by CM000n** [comment] 2023-11-09 13:03
> This [gist](https://gist.github.com/GitOldGrumpy/dd57cbb9e4d8d2871c55e6f98f73cabf) will get you connected to the new toyota services. [...]

Good discovery! The system behind `https://b2c-login.toyota-europe.com/` is probably from [ForgeRock AS](https://www.forgerock.com/) and is only used for identity and access management. I don't think that the telemetry data is also available via this endpoint.

By the way: Authentication is still possible via `https://ssoms.toyota-europe.com/` ;-)

**Comment by GitOldGrumpy** [comment] 2023-11-09 13:23
Yep it is ForgeRock AS and once you have your access token it changes URL from `https://b2c-login.toyota-europe.com` to `https://ctpa-oneapi.tceu-ctp-prd.toyotaconnectedeurope.io`. This has many endpoints to pull information from but seems little point moving forward until I have worked out how to automatically get hold of the GUID(customerId). Can post up later what endpoints I've found and data it is responding with.

**Comment by uphillbattle** [comment] 2023-11-09 13:43
What is the GUID (customerId) format? I haven't been able to locate the `https://cpb2cs.toyota-europe.com/vehicle/user/<This Will Be Your GUID>/...` request, but `https://ssoms.toyota-europe.com` authentication provides both a `uuid` and a `myToyotaId`. The latter is a combination of three letters and five digits (`abc12345`). I take it that the `GUID` is neither of those?

**Comment by GitOldGrumpy** [comment] 2023-11-09 14:02
I start at `https://www.toyota.co.uk/customer/portal#/sso/login/autoclose=true` which logs you in and shows you your cars. I then click on my car(I have developer tools open) and it loads the details for the car. In the developer tools network view there are two requests for a URL starting with my cars Vin number if you look at the request URL under headers you should see the GUID. Its format is `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.

Hopefully you can find it and then confirm that it is working for you.

**Comment by CM000n** [comment] 2023-11-09 14:44
I think it is using the UUID from the single sign on as GUID @GitOldGrumpy.
Please have a look at the tojota repo from calmjm:
https://github.com/calmjm/tojota/blob/ed49d83fd6cf2baf1bf528e40c58abd4a461b0c4/tojota.py#L157

**Comment by GitOldGrumpy** [comment] 2023-11-09 15:04
I've just had a look the UUID is the GUID but the access token does not work, which is to be expected. Still confused on where the new app pulls this from...

**Comment by DurgNomis-drol** [comment] 2023-11-09 15:30
@CM000n Sounds good if this fixes it! But I don't have an answer regarding `ha_toyota`. Some part of it is ported over on this branch https://github.com/DurgNomis-drol/ha_toyota/tree/v2, but I never finished it. It needs a bit of work to get working. Again, it stalled because I don't have car to test most of the features on. If any one wants to pick it up, they are more then welcome to. And I will help get it working, but right now it is just to much of a task when I can't test most of it locally.

**Comment by GitOldGrumpy** [comment] 2023-11-09 16:41
Updated the gist with some of the endpoints I've found but for some reason I'm not authenticated for them all.

**Comment by HuffYk** [comment] 2023-11-09 17:01
Hi, I was migrated also with my Yaris Cross (2023) (works with new status API endpoint) and RAV4 Plugin (2022) (works only with legacy status endpoint) and HA integration stopped working as described here in comments. However when testing API using mytoyota python lib, I was able to get all needed information. Same with calling directly APIs. Unfortunately I didn't stored all API responses to compare but looks like smart info is missing (status info about locks, lights etc.) so maybe for that is now only special API endpoint.

API endpoint for "connected services": https://cpb2cs.toyota-europe.com/vehicle/user/{{uid}}/vehicle/{{VIN_RAV4}}?legacy=true&services=fud,connected
this endpoint returns:
"connected": false,
"connectedService": {"status": "DISABLED"...}

so maybe this is the reason why HA integration states that connected services are offline? anyhow all other APIs worked well:

location: https://myt-agg.toyota-europe.com/cma/api/users/{{uid}}/vehicle/location
ODO: https://myt-agg.toyota-europe.com/cma/api/vehicle/{{VIN_RAV4}}/addtionalInfo
status: https://myt-agg.toyota-europe.com/cma/api/users/{{uid}}/vehicles/{{VIN_RAV4}}/vehicleStatus
legacy status: https://myt-agg.toyota-europe.com/cma/api/vehicles/{{VIN_RAV4}}/remoteControl/status
trips: https://cpb2cs.toyota-europe.com/api/user/{{uid}}/cms/trips/v2/history/vin/{{VIN_RAV4}}/1
trip: https://cpb2cs.toyota-europe.com/api/user/{{uid}}/cms/trips/v2/{{trip_ID}}/events/vin/{{VIN_RAV4}}
driving stats: https://myt-agg.toyota-europe.com/cma/api/v2/trips/summarize?from=2023-01-01&calendarInterval=month

as stated cannot compare API results but one big difference I see is that "status endpoint" for new cars now doesn't show lock/light statuses... results is exactly same as for older vehicle... 

I had one issue before with my RAV4 that it didn't show any legacy information which was available in mytoyota lib
(e.g. it showed only EvTravelableDistance but not GasolineTravelableDistance and also all other info available here in json generated by mytoyota python lib was missing...  Thats why I asked in antoher github issue to update HA integration to latest mytoyota plugin... I don't have knowledge how to do it yet. Already tried to force HA use latest mytoyota python lib, but HA integration started to return errors and didn't work at all so there might be some compatibility issues when using latest mytoyota lib (0.9.2) and the one used by HA_toyota integration (0.7.8):

`        "VehicleInfo": {
            "AcquisitionDatetime": "2023-11-09T13:48:27Z",
            "RemoteHvacInfo": {
                "InsideTemperature": 25,
                "RemoteHvacMode": 0,
                "RemoteHvacProhibitionSignal": 1,
                "SettingTemperature": 21.0,
                "BlowerStatus": 0,
                "FrontDefoggerStatus": 0,
                "RearDefoggerStatus": 0,
                "LatestAcStartTime": "2023-11-09T05:39:15Z",
                "TemperatureDisplayFlag": 1,
                "Temperaturelevel": 32
            },
            "ChargeInfo": {
                "GasolineTravelableDistanceUnit": 1,
                "GasolineTravelableDistance": 507,
                "PlugInHistory": 33,
                "RemainingChargeTime": 65535,
                "EvTravelableDistance": 0.0,
                "EvTravelableDistanceSubtractionRate": 2,
                "ChargeRemainingAmount": 30,
                "SettingChangeAcceptanceStatus": 0,
                "ChargeType": 15,
                "ChargeWeek": 0,
                "ChargeStartTime": "42:35",
                "ChargeEndTime": "42:35",
                "ConnectorStatus": 2,
                "BatteryPowerSupplyPossibleTime": 16383,
                "ChargingStatus": "none",
                "EvDistanceWithAirCoInKm": 0.0,
                "PlugStatus": 12,
                "EvDistanceInKm": 0.0
            }
        },
        "ReturnCode": "000000"
`

**Comment by CM000n** [comment] 2023-11-09 21:26
Hi @DurgNomis-drol and @HuffYk,

I just created a tag for testing the update to mytoyota 0.9.2 within the ha_toyota custom integration: https://github.com/DurgNomis-drol/ha_toyota/releases/tag/v2.0.0-testing
The tag uses the V2 branch as a basis.
I think this makes testing easier in combination with HACS. I hope that's okay @DurgNomis-drol?

I also don't have much time at the moment, but I'll see how much of it I can spare for ha_toyota in the meantime :wink:

Unfortunately updating to the new mytoyota version it's a bit of trial and error because we don't have good unit tests for the custom integration and writing them is unfortunately a bit of a PITA. So any help is more than welcome!

**Comment by HuffYk** [comment] 2023-11-09 23:12
Hi @CM000n, did few tests.

Looks like some changes from master branch have to be merged first. e.g. I had to fix deprecated async_setup_platforms with 

`await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`

Maybe some other changes from master should be merged also? I temporary fixed mytoyota lib to overcome "connected services" issue and now HA integration connected successfully, but it received only location for each car nothing else. And in log there are these errors (enabled also debugging):

```
ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform toyota.binary_sensor: Platform not found (cannot import name 'ToyotaEntityDescription' from 'custom_components.toyota.entity' (/config/custom_components/toyota/entity.py)).

ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota/sensor.py", line 270, in async_setup_entry
ToyotaStatisticsSensor(
File "/config/custom_components/toyota/sensor.py", line 321, in __init__
self.period = description.period
^^^^^^^^^^^^^^^^^^
AttributeError: 'ToyotaSensorEntityDescription' object has no attribute 'period'


```

not sure if it is because something has to be merged from master what was already fixed or it is connected with new mytoyota lib

**Comment by CM000n** [comment] 2023-11-10 06:05
> Hi @CM000n, did few tests.
> 
> Looks like some changes from master branch have to be merged first. e.g. I had to fix deprecated async_setup_platforms with


The master branch ist already merged 😉

**Comment by HuffYk** [comment] 2023-11-10 07:26
If I compare e.g. __init__.py from master (https://github.com/DurgNomis-drol/ha_toyota/pull/131 ) with v2.0.0.0-testing there are many changes missing e.g. mentioned 

`await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`

introduces in v1.2.11 release (https://github.com/DurgNomis-drol/ha_toyota/pull/126/files )

**Comment by HuffYk** [comment] 2023-11-10 07:50
did some testing with official v1.2.11, I patched mytoyota lib to overcome "connected services" issue and now I was able to receive other sensors:

RAV4 Plugin (2022) - older legacy API (not available status of locks or lights in API)
- statistics sensors (current week/month/year)
- front/rear defogger
- fuel tank
- ODO meter
- EV battery status (only "none" but it was also before migration)
- HVAC (only "Unknown" but it was also before migration)
- number plate
- location

missing sensors what I remember:
- Range (before migration I saw at least EV travel distance)

Yaris Cross (2023) - new API (status of locks and lights is available in API)
- statistics sensors (current week/month/year)
- fuel tank
- ODO meter
- location

missing sensors what I remember:
- lights/locks statuses

**Comment by CM000n** [comment] 2023-11-10 08:16
> Hi @CM000n
> 
> If I compare e.g. `__init__.py` from master (#131 ) with v2.0.0-testing there are many changes missing e.g. mentioned [...]

Yes, I think some of the incoming and existing changes were lost during the merge when the merge conflicts were resolved.
We need to look at this again in general and sort it out.

**Comment by HuffYk** [comment] 2023-11-10 08:44
> I've just had a look the UUID is the GUID but the access token does not work, which is to be expected. Still confused on where the new app pulls this from...

I use e.g. this: `https://cpb2cs.toyota-europe.com/vehicle/user/{{uid}}/vehicles` and uid is coming from `https://ssoms.toyota-europe.com/authenticate` as @CM000n wrote...

**Comment by uphillbattle** [comment] 2023-11-10 10:57
> 5. locate `def _has_connected_services_enabled` function and replace this:
> 
> ```
>                 _LOGGER.error(
>                     "Please setup Connected Services if you want live data from the car. (%s)",
>                     censor_vin(self.vin),
>                 )
>                 return False
> ```
> 
> with this:
> 
> ` return True`

That's great! With this "dirty" fix and v1.2.11, I get the data I need: I use the integration for controlling the charging (it's a bZ4x, so an EV), and I can find the "remaining charge" as a attribute to the `EV battery status` sensor. This temporarily solves the problem for me, but I'm hoping we'll be able to fix the integration properly in the days to come 👍

**Comment by HuffYk** [comment] 2023-11-10 17:37
Hi @CM000n 

would it be possible to add back v2.0.0-testing tag ? I would like to test during weekend, but not in my production env (where I installed it yesterday), but rather I created dev env in RPI so would like to install it there from UI rather than manually updating all needed files in shell. thanks!

**Comment by CM000n** [comment] 2023-11-10 17:57
Hi @HuffYk,

No, the tags don't make much sense, as I found out when so many changes are made. The best way to test this is to pull the latest version of the Repo / V2 branch and manually replace the "toyota" folder in the custom components directory of your Home Assistant installation.

**Comment by HuffYk** [comment] 2023-11-10 20:41
ok understand, no problem

**Comment by HuffYk** [comment] 2023-11-11 23:33
@CM000n let me know if I can do testing. I tried latest V2 and getting this errors in log:

```
2023-11-12 00:28:57.005 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up toyota platform for binary_sensor
File "/config/custom_components/toyota/binary_sensor.py", line 307, in async_setup_entry
ToyotaBinarySensor(
File "/config/custom_components/toyota/entity.py", line 30, in __init__
self.vehicle: Vehicle = coordinator.data[self.index]["data"]
~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not Vehicle
```

and few `TypeError: 'NoneType' object is not callable` errors I suppose related to 1st one mentioned above.

In UI I'm able to see locations and few sensors all with unavailable or unknown status.

**Comment by CM000n** [comment] 2023-11-12 07:00
Hi @HuffYk, thank you very much. I am already aware of that. Please see the comment in the associated pull request.
I think we should move further discussions regarding the custom integration update to the new mytoyota version there, as they are no longer directly related to the issue reported here.

**Comment by GitOldGrumpy** [comment] 2023-11-14 15:17
Were have we moved discussions too? I can pull from the new endpoints all most all of the information relevant to my cars(which is everything I could get on the old endpoints plus all the trip details) but to move forward need some help getting hold of further endpoints and either integrating the new endpoint into the current mytoyota or creating something new?

**Comment by DurgNomis-drol** [comment] 2023-11-14 15:21
Please open an PR in https://github.com/DurgNomis-drol/mytoyota so we can start implementing the new API endpoints

**Closed** 2023-11-16 10:23 UTC
Labels: bug
