### ISSUE TITLE
The integration dont load the sensors

### ISSUE THREAD

**Issue by AdrianStanciu22** [DurgNomis-drol/ha_toyota#103] opened 2022-03-27 19:27 UTC
Logger: homeassistant.components.sensor
Source: custom_components/toyota/sensor.py:41
Integration: Sensor (documentation, issues)
First occurred: 9:21:02 PM (2 occurrences)
Last logged: 9:30:03 PM

Error while setting up toyota platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toyota/sensor.py", line 41, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
TypeError: 'NoneType' object is not iterable

**Comment by DurgNomis-drol** [comment] 2022-03-27 19:35
Duplicate of #101

**Closed** 2022-03-27 19:35 UTC
