### ISSUE TITLE
"Detected blocking call" error in log (v2.0.5)

### ISSUE THREAD

**Issue by ccristal** [DurgNomis-drol/ha_toyota#307] opened 2024-11-17 11:19 UTC
I can see an error in the log:

```
2024-11-17 03:06:45.934 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/root/.cache/toyota_credentials_cache_contains_secrets', 'w') inside the event loop by custom integration 'toyota' at custom_components/toyota/__init__.py, line 77: vehicles = await asyncio.wait_for(client.get_vehicles(metric=metric_values), 15) (offender: /usr/local/lib/python3.12/site-packages/mytoyota/controller.py, line 203: with open(str(CACHE_FILENAME), "w", encoding="utf-8") as f:), please create a bug report at https://github.com/DurgNomis-drol/ha_toyota/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 77, in async_get_vehicle_data
    vehicles = await asyncio.wait_for(client.get_vehicles(metric=metric_values), 15)


```

**Comment by CM000n** [comment] 2024-11-25 16:01
Duplicate of https://github.com/DurgNomis-drol/ha_toyota/issues/271

**Closed by CM000n** 2024-11-25 16:01 UTC
Labels: :bug: bug
