### ISSUE TITLE
Language code invalid upon installing, but field is not available for editing...

### ISSUE THREAD

**Issue by renewoensdregt** [DurgNomis-drol/ha_toyota#82] opened 2021-11-13 17:36 UTC
**Describe the bug**
Hi there. I got an error and re-installed the add-on through HACS in home assistant. When putting user and password, the 

Version installed is v1.2.3 on HACS 1.17.0

**To Reproduce**

1. Go to configuration - Integrations
2. Click on add integration and then find Toyota connected services
3. enter user an password and click submit.
4. I then get the error language code is not valid

![image](https://user-images.githubusercontent.com/54376490/141653514-48b6b3ce-8d5f-4e0d-b825-e2eba3fe4c5f.png)

**Expected behavior**
Either language code is automatically - and correctly selected or should be entered manually... .

**Additional context**

**Comment by DurgNomis-drol** [comment] 2021-11-13 19:45
Duplicate of #75

Follow #75 for updates

**Comment by renewoensdregt** [comment] 2021-11-13 20:31
Thanks. Did not see this in the list of issues! Not sure why!

**Comment by DurgNomis-drol** [comment] 2021-11-13 21:08
Just noticed it was closed, just reopened it. Thought it was open, so no worry 😊

**Comment by renewoensdregt** [comment] 2021-11-13 21:11
But shouldn't you close it as it's the same as the other issue you referred to? I'll follow that one and if I have to test something, happy to help. I think it's caused by the latest HA updates as even going back a version I'm still getting the same issue.

**Comment by DurgNomis-drol** [comment] 2021-11-13 22:59
It is me who are stupid 🤦‍♂️ on mobile and not looking at what issue I replied too....

**Closed** 2021-11-13 22:59 UTC
