### ISSUE TITLE
Error while setting up toyota platform for device_tracker

### ISSUE THREAD

**Issue by RohlikX** [DurgNomis-drol/ha_toyota#102] opened 2022-03-26 05:54 UTC
Logger: homeassistant.components.sensor
Source: custom_components/toyota/sensor.py:41
Integration: Senzor (documentation, issues)
First occurred: 24. března 2022 16:23:45 (2 occurrences)
Last logged: 06:52:30

Error while setting up toyota platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toyota/sensor.py", line 41, in async_setup_entry
    for index, _ in enumerate(coordinator.data):
TypeError: 'NoneType' object is not iterable

**Comment by DurgNomis-drol** [comment] 2022-03-26 11:45
Duplicate of #101

**Closed** 2022-03-26 11:45 UTC
